
**Задание 1**
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [43]:
import numpy as np
n = 10
a = np.arange(0, n, 1)
-np.sort(-a)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


**Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [46]:
N = 10
a = np.arange(0, n, 1)
z = -np.sort(-a)
np.diag(z, k=0)     
np.diag(np.arange(N), k=0)
print(z)
np.trace(a)


[9 8 7 6 5 4 3 2 1 0]


ValueError: diag requires an array of at least two dimensions

**Задание 3**
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [37]:

a = np.array( [ [4, 2, 1], [1, 3, 0] , [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])